export const projectTemplates = [
  {
    id: "website",
    name: "Website Development",
    description: "Marketing sites, corporate websites, portals, and commerce experiences.",
    color: "#5B67D6",
    categoryName: "Website Delivery",
    subcategories: [
      "Discovery & Sitemap",
      "Content & Information Architecture",
      "UI/UX Design",
      "Frontend Development",
      "CMS & Backend",
      "Forms, APIs & Integrations",
      "Responsive, Accessibility & Browser QA",
      "Performance, Security & Analytics",
      "Launch & Handover",
    ],
    milestoneSuggestions: [
      "Discovery approved",
      "UX and visual design approved",
      "Development feature complete",
      "Content and integrations complete",
      "Quality assurance and UAT complete",
      "Production launch and handover",
    ],
  },
  {
    id: "crm",
    name: "CRM Development",
    description: "Customer lifecycle, sales, service, automation, and reporting platforms.",
    color: "#00897B",
    categoryName: "CRM Delivery",
    subcategories: [
      "Process Discovery & Requirements",
      "Customer & Sales Data Model",
      "Lead, Pipeline & Opportunity Management",
      "Workflow & Communication Automation",
      "Roles, Permissions & Audit Trail",
      "Dashboards & Reporting",
      "Third-party Integrations",
      "Data Migration & Cleansing",
      "QA, UAT & Training",
      "Go-live & Adoption",
    ],
    milestoneSuggestions: [
      "Business processes approved",
      "Solution and data model approved",
      "Core CRM workflows complete",
      "Integrations and migration complete",
      "UAT and training complete",
      "Go-live and adoption review",
    ],
  },
  {
    id: "erp",
    name: "ERP Development",
    description: "Integrated operations covering finance, inventory, procurement, HR, and reporting.",
    color: "#7B1FA2",
    categoryName: "ERP Delivery",
    subcategories: [
      "Business Process Mapping",
      "Solution Architecture & Master Data",
      "Finance & Accounting",
      "Inventory & Warehouse",
      "Procurement & Vendor Management",
      "Sales, Orders & Fulfilment",
      "HR & Administration",
      "Integrations & Data Migration",
      "Security, Controls & Compliance",
      "UAT, Training & Cutover",
    ],
    milestoneSuggestions: [
      "Process blueprint approved",
      "Architecture and master data approved",
      "Core modules feature complete",
      "Integrations and migration rehearsal complete",
      "UAT and operational training complete",
      "Cutover and hypercare complete",
    ],
  },
  {
    id: "mobile-app",
    name: "Mobile App Development",
    description: "Native or cross-platform iOS and Android products with backend services.",
    color: "#EF6C00",
    categoryName: "Mobile App Delivery",
    subcategories: [
      "Product Discovery & User Flows",
      "Mobile UI/UX & Design System",
      "iOS & Android Development",
      "Backend, APIs & Authentication",
      "Notifications & Device Capabilities",
      "Offline Data & Synchronization",
      "Analytics, Privacy & Security",
      "Device, Performance & Accessibility QA",
      "Beta Distribution & UAT",
      "App Store Release & Monitoring",
    ],
    milestoneSuggestions: [
      "Product scope and user flows approved",
      "Prototype and design system approved",
      "Core application feature complete",
      "Backend and integrations complete",
      "Beta testing and UAT complete",
      "Store release and monitoring live",
    ],
  },
  {
    id: "custom-software",
    name: "Custom Software Development",
    description: "Purpose-built web platforms, internal tools, automations, and integrations.",
    color: "#1565C0",
    categoryName: "Custom Software Delivery",
    subcategories: [
      "Discovery & Business Analysis",
      "Product Scope & Acceptance Criteria",
      "Architecture & Technical Design",
      "UI/UX & Prototyping",
      "Application Development",
      "APIs, Integrations & Automation",
      "Data, Migration & Reporting",
      "Security, Performance & Reliability",
      "QA, UAT & Documentation",
      "Deployment, Training & Support",
    ],
    milestoneSuggestions: [
      "Discovery and scope approved",
      "Architecture and UX approved",
      "Core product feature complete",
      "Integrations and data complete",
      "QA and UAT complete",
      "Production release and handover",
    ],
  },
];

export const getProjectTemplate = (templateId) =>
  projectTemplates.find((template) => template.id === templateId) || null;

export const getTemplateForCategory = (categoryName) =>
  projectTemplates.find((template) => template.categoryName === categoryName) || null;

export const defaultCategories = projectTemplates.map((template) => ({
  id: `template-${template.id}`,
  name: template.categoryName,
  color: template.color,
  description: `${template.name}: ${template.description}`,
  projectType: template.id,
  systemTemplate: true,
  subcategories: template.subcategories.map((name) => ({ name, tasks: [] })),
}));

export default projectTemplates;
